name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    uses: actions/hello-world-docker-action@v1
    with:
      who-to-greet: 'Mona the Octocat'